<?php
/*
##############################################################
Internationalization for Typesetter CMS addon 'Hide Admin UI'
Author: J. Krausz
Date: 2018-01-15
Version 1.1

Please help! We appreciate any improvements to the translation

##############################################################
*/



$HideAdminUI_i18n = array(

  // Afrikaans
  'af' => array(
    'Hide Admin UI'             => 'Versteek Admin UI',
    'Show Admin UI'             => 'Wys Admin UI',
    'Keyboard Shortcut'         => 'Sleutelbordkortpaaie',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // العربية/Arabic
  'ar' => array(
    'Hide Admin UI'             => 'إخفاء واجهة مستخدم المشرف',
    'Show Admin UI'             => 'إظهار واجهة مستخدم المشرف',
    'Keyboard Shortcut'         => 'اختصار لوحة المفاتيح',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => 'Shift',
  ),

  // Български/Bulgarian
  'bg' => array(
    'Hide Admin UI'             => 'Скриване на Aдмин UI',
    'Show Admin UI'             => 'Показване на Aдмин UI',
    'Keyboard Shortcut'         => 'Клавишна комбинация',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Català/Catalan
  'ca' => array(
    'Hide Admin UI'             => 'Amaga la Admin UI',
    'Show Admin UI'             => 'Mostra la Admin UI',
    'Keyboard Shortcut'         => 'Tecla de drecera',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Česky/Czech
  'cs' => array(
    'Hide Admin UI'             => 'Skrýt Admin UI',
    'Show Admin UI'             => 'Zobrazit Admin UI',
    'Keyboard Shortcut'         => 'Klávesová zkratka',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Dansk
  'da' => array(
    'Hide Admin UI'             => 'Skjul Admin UI',
    'Show Admin UI'             => 'Vis Admin UI',
    'Keyboard Shortcut'         => 'Tastaturgenvej',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Deutsch/German
  'de' => array(
    'Hide Admin UI'             => 'Admin UI ausblenden',
    'Show Admin UI'             => 'Admin UI einblenden',
    'Keyboard Shortcut'         => 'Tastaturkurzbefehl',
    'Ctrl'                      => 'Strg',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Ελληνικά/Greek
  'el' => array(
    'Hide Admin UI'             => 'Απόκρυψη διαχειριστή UI',
    'Show Admin UI'             => 'Εμφάνιση διαχειριστή UI',
    'Keyboard Shortcut'         => 'Συντόμευση πληκτρολογίου',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // English(default)
  'en' => array(
    'Hide Admin UI'             => 'Hide Admin UI',
    'Show Admin UI'             => 'Show Admin UI',
    'Keyboard Shortcut'         => 'Keyboard Shortcut',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Español/Spanish
  'es' => array(
    'Hide Admin UI'             => 'Ocultar de Admin UI',
    'Show Admin UI'             => 'Mostrar de Admin UI',
    'Keyboard Shortcut'         => 'Klaviatuuri otsetee',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // eesti/Estonian
  'et' => array(
    'Hide Admin UI'             => 'Peida Admin UI',
    'Show Admin UI'             => 'Admin UI näitamine',
    'Keyboard Shortcut'         => 'XXX',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Suomi/Finnish
  'fi' => array(
    'Hide Admin UI'             => 'Piilota Admin UI',
    'Show Admin UI'             => 'Näytä Admin UI',
    'Keyboard Shortcut'         => 'Näppäinoikeus',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Føroyskt/Faroese
  'fo' => array(
    'Hide Admin UI'             => 'Fjala Admin UI',
    'Show Admin UI'             => 'Sýna Admin UI',
    'Keyboard Shortcut'         => 'Knappaborð stytting',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Français/French
  'fr' => array(
    'Hide Admin UI'             => 'Masquer l\'interface utilisateur d\'administration',
    'Show Admin UI'             => 'Afficher l\'interface utilisateur d\'administration',
    'Keyboard Shortcut'         => 'Raccourci clavier',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Galego/Galician
  'gl' => array(
    'Hide Admin UI'             => 'Ocultar a Admin UI',
    'Show Admin UI'             => 'Mostrar a Admin UI',
    'Keyboard Shortcut'         => 'Atallo de teclado',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // hrvatski/Croatian
  'hr' => array(
    'Hide Admin UI'             => 'Sakrij Admin UI',
    'Show Admin UI'             => 'Prikaži Admin UI',
    'Keyboard Shortcut'         => 'Prečac na tipkovnici',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Magyar/Hungarian
  'hu' => array(
    'Hide Admin UI'             => 'Admin UI elrejtése',
    'Show Admin UI'             => 'Admin UI megjelenítése',
    'Keyboard Shortcut'         => 'Billentyűparancs',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Italiano/Italian
  'it' => array(
    'Hide Admin UI'             => 'Nascondere Admin UI',
    'Show Admin UI'             => 'Mostrare Admin UI',
    'Keyboard Shortcut'         => 'Scorciatoia da tastiera',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // 日本語/Japanese
  'ja' => array(
    'Hide Admin UI'             => '管理UIを非表示',
    'Show Admin UI'             => '管理UIを表示する',
    'Keyboard Shortcut'         => 'キーボードショートカット',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Lietuvių/Lithuanian
  'lt' => array(
    'Hide Admin UI'             => 'Slėpti Admin UI',
    'Show Admin UI'             => 'Rodyti Admin UI',
    'Keyboard Shortcut'         => 'Spartieji klavišai',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Nederlands/Dutch
  'nl' => array(
    'Hide Admin UI'             => 'Admin UI verbergen',
    'Show Admin UI'             => 'Toon Admin UI',
    'Keyboard Shortcut'         => 'Toetsenbord sneltoets',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Norsk/Norwegian
  'no' => array(
    'Hide Admin UI'             => 'Skjul Admin UI',
    'Show Admin UI'             => 'Vis Admin UI',
    'Keyboard Shortcut'         => 'Tastaturgenvei',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Polski/Polish
  'pl' => array(
    'Hide Admin UI'             => 'Ukryj Admin UI',
    'Show Admin UI'             => 'Pokaż Admin UI',
    'Keyboard Shortcut'         => 'Skrót klawiszowy',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Português/Portuguese
  'pt' => array(
    'Hide Admin UI'             => 'Ocultar Admin UI',
    'Show Admin UI'             => 'Mostrar Admin UI',
    'Keyboard Shortcut'         => 'Atalho do teclado',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Português do Brasil/Brazilian Portuguese
  'pt-br' => array(
    'Hide Admin UI'             => 'Ocultar Admin UI',
    'Show Admin UI'             => 'Mostrar Admin UI',
    'Keyboard Shortcut'         => 'Atalho do teclado',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Română/Romanian
  'ro' => array(
    'Hide Admin UI'             => 'Ascunde Admin UI',
    'Show Admin UI'             => 'Afișează Admin UI',
    'Keyboard Shortcut'         => 'Comanda rapidă de la tastatură',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Русский/Russian
  'ru' => array(
    'Hide Admin UI'             => 'Скрыть Aдмин UI',
    'Show Admin UI'             => 'Показать пользовательский Aдмин UI',
    'Keyboard Shortcut'         => 'Сочетание клавиш',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Slovenčina/Slovak
  'sk' => array(
    'Hide Admin UI'             => 'Skryť Admin UI',
    'Show Admin UI'             => 'Zobraziť Admin UI',
    'Keyboard Shortcut'         => 'Klávesová skratka',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Slovenščina/Slovenian
  'sl' => array(
    'Hide Admin UI'             => 'Skrij Admin UI',
    'Show Admin UI'             => 'Pokaži Admin UI',
    'Keyboard Shortcut'         => 'Bližnjica na tipkovnici',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Svenska/Swedish
  'sv' => array(
    'Hide Admin UI'             => 'Dölj Admin UI',
    'Show Admin UI'             => 'Visa Admin UI',
    'Keyboard Shortcut'         => 'Tangentbordsgenväg',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Türkçe/Turkish
  'tr' => array(
    'Hide Admin UI'             => 'Admin UI gizle',
    'Show Admin UI'             => 'Admin UI Göster',
    'Keyboard Shortcut'         => 'Klavye kısayolu',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // Українська/Ukrainian
  'uk' => array(
    'Hide Admin UI'             => 'Сховати Aдмін UI',
    'Show Admin UI'             => 'Показати Aдмін UI',
    'Keyboard Shortcut'         => 'Kомбінація клавіш',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => '&uArr;',
  ),

  // 中文/Zhōng Wén/Chinese
  'zh' => array(
    'Hide Admin UI'             => '隐藏管理界面',
    'Show Admin UI'             => '显示管理界面',
    'Keyboard Shortcut'         => '键盘快捷键',
    'Ctrl'                      => 'Ctrl',
    'Alt'                       => 'Alt',
    'Shift'                     => 'Shift',
  ),

);
